services:
  - type: web
    name: wms-backend
    runtime: python
    repo: https://github.com/nitindaswani/WMS
    rootDir: Backend
    buildCommand: ./build.sh
    startCommand: gunicorn wms_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: wms-db
    databaseName: wms_db
    user: wms_user
